[html]
validator = "tidy" # Can currently only be 'tidy', make sure you have a version of tidy installed that supports html5

[html.tidy]
input-xml = "true"
doctype = "html5"
output-xhtml = "true"
show-warnings = "false"


[log]
filename = "cpld.log"
level = "DEBUG"